Repository AutoEverFlipFlick/FlipFlick_FE, pull requests merged in 2025-07, with the labels that each got.

#89 [REFAC] 통합 검색 페이지 회원 연결
  src/pages/TotalSearch.tsx
Labels: REFAC

#90 [FEAT] 비밀번호 재설정
  src/assets/common/background2.webp
  src/pages/member/EmailLogin.tsx
  src/pages/member/FindPassword.tsx
  src/pages/member/Login.tsx
  src/pages/member/ResetPassword.tsx
  src/pages/member/SignUp.tsx
  src/pages/member/SocialSignUp.tsx
  src/router/index.tsx
  src/services/member.ts
Labels: FEAT

#96 [FIX] 관리자 페이지 수정 및 프로필 이미지 수정
  src/components/common/BaseHeaderVer2.tsx
  src/context/AuthContext.tsx
  src/pages/admin/AdminLayout.tsx
Labels: FIX

#102 [FEAT] BaseInput(Ver2) 모바일 대응 반응형 완성
  src/assets/category/record.png
  src/components/common/BaseHeaderVer2.tsx
  src/styles/variables.css
  src/utils/breakpoints.ts
Labels: FEAT

#103 [RELEASE] Main 코드 업데이트
  src/assets/category/record.png
  src/assets/common/background2.webp
  src/components/common/BaseHeaderVer2.tsx
  src/components/common/layout/NoHeaderLayout.tsx
  src/context/AuthContext.tsx
  src/pages/Bolkinator.tsx
  src/pages/TotalSearch.tsx
  src/pages/admin/AdminLayout.tsx
  src/pages/filmography.tsx
  src/pages/member/EmailLogin.tsx
  src/pages/member/FindPassword.tsx
  src/pages/member/KakaoRedirectHandler.tsx
  src/pages/member/Login.tsx
  src/pages/member/NaverRedirectHandler.tsx
  src/pages/member/ResetPassword.tsx
  src/pages/member/SignUp.tsx
  src/pages/member/SocialSignUp.tsx
  src/pages/playlist/PlaylistDetail.tsx
  src/router/index.tsx
  src/services/axiosInstance.ts
  src/services/member.ts
  src/styles/variables.css
  src/utils/breakpoints.ts
Labels: RELEASE

#107 [FIX] 통합 검색 페이지 영화 페이지 연결
  src/pages/TotalSearch.tsx
Labels: FIX

#108 [RELEASE] Main 코드 업데이트
  src/components/common/BaseHeaderVer2.tsx
  src/pages/TotalSearch.tsx
Labels: RELEASE

#122 [FEAT] 토론 작성 페이지 구현
  package-lock.json
  package.json
  src/pages/debate/DebateWritePage.tsx
  src/pages/member/EmailLogin.tsx
  src/pages/playlist/CreatePlaylist.tsx
  src/pages/playlist/EditPlaylist.tsx
  src/pages/playlist/PlaylistDetail.tsx
  src/router/index.tsx
  src/services/axiosInstance.ts
  src/services/debate.ts
Labels: FEAT

#128 [FEAT] 정지, 차단 예외 처리
  src/components/common/AdminRoute.tsx
  src/components/common/ProtectedRoute.tsx
  src/components/common/PublicRoute.tsx
  src/pages/member/EmailLogin.tsx
  src/pages/member/KakaoRedirectHandler.tsx
  src/pages/member/NaverRedirectHandler.tsx
  src/services/axiosInstance.ts
Labels: FEAT

#130 [RELEASE] Main 코드 업데이트
  package-lock.json
  package.json
  src/assets/home/jukebox-final.webp
  src/assets/home/jukebox-top.webp
  src/assets/home/wavve-seeklogo.svg
  src/components/common/AdminRoute.tsx
  src/components/common/BaseHeaderVer2.tsx
  src/components/common/ProtectedRoute.tsx
  src/components/common/PublicRoute.tsx
  src/components/feature/MovieSearchModal.tsx
  src/components/feature/home/OttButton.tsx
  src/pages/Home.tsx
  src/pages/debate/DebateWritePage.tsx
  src/pages/filmography.tsx
  src/pages/member/EmailLogin.tsx
  src/pages/member/KakaoRedirectHandler.tsx
  src/pages/member/NaverRedirectHandler.tsx
  src/pages/myPage/MyPageDebate.tsx
  src/pages/myPage/MyPageEdit.tsx
  src/pages/myPage/MyPageFollowList.tsx
  src/pages/myPage/MyPageMain.tsx
  src/pages/myPage/MyPagePreference.tsx
  src/pages/myPage/MyPageReview.tsx
  src/pages/playlist/CreatePlaylist.tsx
  src/pages/playlist/EditPlaylist.tsx
  src/pages/playlist/PlaylistDetail.tsx
  src/router/index.tsx
  src/services/axiosInstance.ts
  src/services/debate.ts
  src/services/movie.ts
Labels: RELEASE

#132 [RELEASE] Main 코드 업데이트
  src/assets/platform/disney_plus.png
  src/assets/platform/netflix.png
  src/assets/platform/watcha.png
  src/assets/platform/wavve.png
  src/components/feature/movieDetail/ReviewCard.tsx
  src/components/feature/movieDetail/ReviewDebateCard.tsx
  src/pages/movie/MovieDetailPage.tsx
  src/pages/movie/ReviewTextArea.tsx
  src/pages/movie/debateData.ts
  src/pages/movie/reviewData.ts
  src/router/index.tsx
  src/services/movieDetail.ts
Labels: RELEASE

#135 [FEAT] 토론 관련 페이지 구현
  src/App.tsx
  src/components/common/BaseHeaderVer2.tsx
  src/context/AuthContext.tsx
  src/pages/admin/AdminLayout.tsx
  src/pages/admin/ReportDetailModal.tsx
  src/pages/debate/DebateDetailPage.tsx
  src/pages/debate/PopcornIcon.tsx
  src/pages/member/EmailLogin.tsx
  src/pages/member/KakaoRedirectHandler.tsx
  src/pages/member/NaverRedirectHandler.tsx
  src/router/index.tsx
  src/services/debate.ts
  src/services/member.ts
Labels: FEAT

#137 [RELEASE] Main 코드 업데이트
  src/App.tsx
  src/components/common/BaseHeaderVer2.tsx
  src/context/AuthContext.tsx
  src/pages/admin/AdminLayout.tsx
  src/pages/admin/ReportDetailModal.tsx
  src/pages/debate/DebateDetailPage.tsx
  src/pages/debate/PopcornIcon.tsx
  src/pages/member/EmailLogin.tsx
  src/pages/member/KakaoRedirectHandler.tsx
  src/pages/member/NaverRedirectHandler.tsx
  src/router/index.tsx
  src/services/debate.ts
  src/services/member.ts
Labels: RELEASE

#140 [RELEASE] Main 코드 업데이트
  src/components/common/BaseHeaderVer2.tsx
  src/pages/myPage/MyPageDebate.tsx
  src/pages/myPage/MyPageEdit.tsx
  src/pages/myPage/MyPageFollowList.tsx
  src/pages/myPage/MyPageMain.tsx
  src/pages/myPage/MyPagePreference.tsx
  src/pages/myPage/MyPageReview.tsx
  src/services/memberPost.ts
Labels: RELEASE

#144 [FIX] 토론 카드 수정
  src/components/feature/movieDetail/DebateCard.tsx
  src/pages/movie/MovieDetailPage.tsx
Labels: FIX

#146 [Feat] 영화 상세 5차 구현
  src/components/feature/movieDetail/ReviewDebateCard.tsx
  src/pages/debate/DebateWritePage.tsx
  src/pages/movie/MovieDetailPage.tsx
  src/pages/movie/debateData.ts
  src/pages/movie/movieApiExample.json
  src/pages/movie/movieData.ts
  src/pages/movie/movieDataMapper.ts
  src/pages/movie/reviewData.ts
  src/services/movieDetail.ts
Labels: FEAT

#152 [FIX] 팔로우 화면 오류 수정, 프로필 이미지 변경 시 미리보기 즉시 반영
  src/pages/myPage/MyPageEdit.tsx
  src/pages/myPage/MyPageFollowList.tsx
Labels: FIX

#155 [RELEASE] Main 코드 업데이트
  src/components/common/BaseHeaderVer2.tsx
  src/pages/myPage/MyPageEdit.tsx
  src/pages/myPage/MyPageFollowList.tsx
  src/utils/auth/tokenObserver.ts
Labels: RELEASE

#160 [FEAT] 플레이리스트 기능 구현
  src/components/feature/PlaylistAddModal.tsx
  src/pages/member/KakaoRedirectHandler.tsx
  src/pages/member/NaverRedirectHandler.tsx
  src/pages/member/SocialSignUp.tsx
  src/pages/movie/MovieDetailPage.tsx
Labels: FEAT

#163 [RELEASE] Main 코드 업데이트
  src/components/common/AlarmListener.tsx
Labels: RELEASE

#168 [FIX] 좋아요 기능 수정
  src/components/feature/movieDetail/ReviewDebateCard.tsx
  src/pages/movie/MovieDetailPage.tsx
  src/pages/movie/reviewData.ts
  src/services/movieDetail.ts
Labels: FIX

#178 [RELEASE] Main 코드 업데이트
  src/pages/movie/ReviewTextArea.tsx
  src/pages/myPage/MyPageDebate.tsx
Labels: RELEASE

#182 [RELEASE] Main 코드 업데이트
  src/pages/movie/MovieDetailPage.tsx
Labels: RELEASE
